apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-05-11T13:44:07Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:run: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl
    operation: Update
    time: "2021-05-11T13:44:07Z"
  name: nginxsvc
  namespace: default
  resourceVersion: "13563"
  uid: 95147e05-42f0-4172-9b7b-806505e79563
spec:
  clusterIP: 10.107.22.225
  clusterIPs:
  - 10.107.22.225
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31001
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: my-nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
