apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  clusterIP: 10.107.22.224
  clusterIPs:
  - 10.107.22.224
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  selector:
    app: mongo